# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainWindow.ui'
#
# Created: Sun Jul  6 18:02:58 2008
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(487,448)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setGeometry(QtCore.QRect(0,28,487,399))
        self.centralwidget.setObjectName("centralwidget")
        self.entrysGroup = QtGui.QGroupBox(self.centralwidget)
        self.entrysGroup.setGeometry(QtCore.QRect(10,10,471,181))
        self.entrysGroup.setObjectName("entrysGroup")
        self.listEntrys = QtGui.QTreeWidget(self.entrysGroup)
        self.listEntrys.setGeometry(QtCore.QRect(10,20,421,151))
        self.listEntrys.setObjectName("listEntrys")
        self.upButton = QtGui.QToolButton(self.entrysGroup)
        self.upButton.setGeometry(QtCore.QRect(440,30,25,25))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/go-up/go-up.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.upButton.setIcon(icon)
        self.upButton.setObjectName("upButton")
        self.downButton = QtGui.QToolButton(self.entrysGroup)
        self.downButton.setGeometry(QtCore.QRect(440,60,25,25))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/go-down/go-down.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.downButton.setIcon(icon)
        self.downButton.setObjectName("downButton")
        self.deleteButton = QtGui.QToolButton(self.entrysGroup)
        self.deleteButton.setGeometry(QtCore.QRect(440,120,25,25))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/application-exit/application-exit.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.deleteButton.setIcon(icon)
        self.deleteButton.setObjectName("deleteButton")
        self.newGroup = QtGui.QGroupBox(self.centralwidget)
        self.newGroup.setGeometry(QtCore.QRect(10,200,261,191))
        self.newGroup.setObjectName("newGroup")
        self.nameLine = QtGui.QLineEdit(self.newGroup)
        self.nameLine.setGeometry(QtCore.QRect(80,20,161,22))
        self.nameLine.setObjectName("nameLine")
        self.discLine = QtGui.QLineEdit(self.newGroup)
        self.discLine.setGeometry(QtCore.QRect(80,60,161,22))
        self.discLine.setObjectName("discLine")
        self.label = QtGui.QLabel(self.newGroup)
        self.label.setGeometry(QtCore.QRect(20,20,50,21))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.newGroup)
        self.label_2.setGeometry(QtCore.QRect(20,60,50,21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.newGroup)
        self.label_3.setGeometry(QtCore.QRect(20,90,50,21))
        self.label_3.setObjectName("label_3")
        self.kernelLine = QtGui.QLineEdit(self.newGroup)
        self.kernelLine.setGeometry(QtCore.QRect(80,90,131,22))
        self.kernelLine.setObjectName("kernelLine")
        self.kernelOpenButton = QtGui.QToolButton(self.newGroup)
        self.kernelOpenButton.setGeometry(QtCore.QRect(220,90,25,25))
        self.kernelOpenButton.setObjectName("kernelOpenButton")
        self.label_4 = QtGui.QLabel(self.newGroup)
        self.label_4.setGeometry(QtCore.QRect(20,130,101,21))
        self.label_4.setObjectName("label_4")
        self.mountLine = QtGui.QLineEdit(self.newGroup)
        self.mountLine.setGeometry(QtCore.QRect(130,130,113,22))
        self.mountLine.setObjectName("mountLine")
        self.addButton = QtGui.QPushButton(self.newGroup)
        self.addButton.setGeometry(QtCore.QRect(170,160,75,26))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/application-ok-apply/dialog-ok-apply.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.addButton.setIcon(icon)
        self.addButton.setObjectName("addButton")
        self.clearButton = QtGui.QPushButton(self.newGroup)
        self.clearButton.setGeometry(QtCore.QRect(70,160,75,26))
        self.clearButton.setObjectName("clearButton")
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(280,210,91,16))
        self.label_5.setObjectName("label_5")
        self.splashLine = QtGui.QLineEdit(self.centralwidget)
        self.splashLine.setGeometry(QtCore.QRect(280,230,151,22))
        self.splashLine.setObjectName("splashLine")
        self.splashOpenButton = QtGui.QToolButton(self.centralwidget)
        self.splashOpenButton.setGeometry(QtCore.QRect(440,230,25,25))
        self.splashOpenButton.setObjectName("splashOpenButton")
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(280,250,50,16))
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0,0,487,28))
        self.menubar.setObjectName("menubar")
        self.menuDosya = QtGui.QMenu(self.menubar)
        self.menuDosya.setObjectName("menuDosya")
        self.menuYard_m = QtGui.QMenu(self.menubar)
        self.menuYard_m.setObjectName("menuYard_m")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setGeometry(QtCore.QRect(0,427,487,21))
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionYapilandir = QtGui.QAction(MainWindow)
        self.actionYapilandir.setObjectName("actionYapilandir")
        self.actionCik = QtGui.QAction(MainWindow)
        self.actionCik.setObjectName("actionCik")
        self.actionEl_kitabi = QtGui.QAction(MainWindow)
        self.actionEl_kitabi.setObjectName("actionEl_kitabi")
        self.actionHakkinda = QtGui.QAction(MainWindow)
        self.actionHakkinda.setObjectName("actionHakkinda")
        self.menuDosya.addAction(self.actionYapilandir)
        self.menuDosya.addAction(self.actionCik)
        self.menuYard_m.addAction(self.actionEl_kitabi)
        self.menuYard_m.addAction(self.actionHakkinda)
        self.menubar.addAction(self.menuDosya.menuAction())
        self.menubar.addAction(self.menuYard_m.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Grub Yöneticisi", None, QtGui.QApplication.UnicodeUTF8))
        self.entrysGroup.setTitle(QtGui.QApplication.translate("MainWindow", "Girdiler", None, QtGui.QApplication.UnicodeUTF8))
        self.listEntrys.headerItem().setText(0,QtGui.QApplication.translate("MainWindow", "Girdi ismi", None, QtGui.QApplication.UnicodeUTF8))
        self.listEntrys.headerItem().setText(1,QtGui.QApplication.translate("MainWindow", "Disk", None, QtGui.QApplication.UnicodeUTF8))
        self.listEntrys.headerItem().setText(2,QtGui.QApplication.translate("MainWindow", "Çekirdek", None, QtGui.QApplication.UnicodeUTF8))
        self.listEntrys.headerItem().setText(3,QtGui.QApplication.translate("MainWindow", "Bağlama yolu", None, QtGui.QApplication.UnicodeUTF8))
        self.upButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.downButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.newGroup.setTitle(QtGui.QApplication.translate("MainWindow", "Yeni girdi", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "İsim:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Disk:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Kernel:", None, QtGui.QApplication.UnicodeUTF8))
        self.kernelOpenButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Bağlama Noktası:", None, QtGui.QApplication.UnicodeUTF8))
        self.addButton.setText(QtGui.QApplication.translate("MainWindow", "Kaydet", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setText(QtGui.QApplication.translate("MainWindow", "Temizle", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Boot arkaplanı:", None, QtGui.QApplication.UnicodeUTF8))
        self.splashOpenButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "(xpm.gz)", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDosya.setTitle(QtGui.QApplication.translate("MainWindow", "Dosya", None, QtGui.QApplication.UnicodeUTF8))
        self.menuYard_m.setTitle(QtGui.QApplication.translate("MainWindow", "Yardım", None, QtGui.QApplication.UnicodeUTF8))
        self.actionYapilandir.setText(QtGui.QApplication.translate("MainWindow", "Yapılandır", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCik.setText(QtGui.QApplication.translate("MainWindow", "Çık", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEl_kitabi.setText(QtGui.QApplication.translate("MainWindow", "El kitabı", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHakkinda.setText(QtGui.QApplication.translate("MainWindow", "Grub Yöneticisi Hakkında", None, QtGui.QApplication.UnicodeUTF8))

import grubicons_rc
